import { useEffect, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { CalendarDays, MessageCircle, Scissors, Sparkles, Users } from "lucide-react";
import { isSupabaseConfigured, supabase } from "./lib/supabase";

type Mode="login"|"signup";
type Shop={id:string;name:string};

function Auth(){const [mode,setMode]=useState<Mode>("login");const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");async function submit(e:React.FormEvent){e.preventDefault();if(!supabase)return setMessage("Configure o Supabase no .env.");setBusy(true);setMessage("");const result=mode==="signup"?await supabase.auth.signUp({email,password,options:{data:{full_name:name}}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(result.error)return setMessage(result.error.message);if(mode==="signup"&&!result.data.session)setMessage("Conta criada. Confira seu e-mail para confirmar o acesso.");}return <div className="auth-page"><div className="auth-brand"><div className="logo">T</div><strong>TENVYQA</strong><span>Business</span></div><div className="auth-card"><p className="eyebrow">EXCLUSIVO PARA BARBEARIAS</p><h1>{mode==="login"?"Bem-vindo de volta":"Crie sua conta"}</h1><p>{mode==="login"?"Entre para gerenciar sua barbearia.":"Comece a configurar sua operação inteligente."}</p><form onSubmit={submit}>{mode==="signup"&&<label>Seu nome<input value={name} onChange={e=>setName(e.target.value)} required placeholder="Nome completo"/></label>}<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="voce@barbearia.com"/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} placeholder="Mínimo 6 caracteres"/></label>{message&&<div className="form-message">{message}</div>}<button disabled={busy}>{busy?"Aguarde...":mode==="login"?"Entrar":"Criar conta"}</button></form><button className="link-button" onClick={()=>{setMode(mode==="login"?"signup":"login");setMessage("")}}>{mode==="login"?"Ainda não tenho conta":"Já tenho uma conta"}</button></div></div>}

function Onboarding({onDone}:{onDone:(shop:Shop)=>void}){const [name,setName]=useState("");const [phone,setPhone]=useState("");const [whatsapp,setWhatsapp]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function submit(e:React.FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError("");const {data,error}=await supabase.rpc("create_barbershop_for_current_user",{shop_name:name,shop_phone:phone||null,shop_whatsapp:whatsapp||null});setBusy(false);if(error)return setError(error.message);onDone({id:data as string,name});}return <div className="auth-page"><div className="onboarding-card"><div className="step">PASSO 1 DE 7</div><h1>Vamos configurar sua barbearia</h1><p>Esses dados serão a base do atendimento e dos próximos passos.</p><form onSubmit={submit}><label>Nome da barbearia<input value={name} onChange={e=>setName(e.target.value)} required placeholder="Ex.: Barbearia Central"/></label><div className="form-row"><label>Telefone<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(21) 99999-9999"/></label><label>WhatsApp<input value={whatsapp} onChange={e=>setWhatsapp(e.target.value)} placeholder="(21) 99999-9999"/></label></div>{error&&<div className="form-message">{error}</div>}<button disabled={busy}>{busy?"Criando...":"Criar minha barbearia"}</button></form></div></div>}

const cards=[["Agendamentos hoje","0",CalendarDays],["Conversas hoje","0",MessageCircle],["Novos clientes","0",Users],["Barbeiros ativos","0",Scissors]] as const;
function Dashboard({shop}:{shop:Shop}){return <div className="shell"><aside><div className="brand"><span>T</span><div><strong>TENVYQA</strong><small>Business</small></div></div><div className="shop-name">{shop.name}</div><nav><a className="active">Dashboard</a><a>Conversas</a><a>Agenda</a><a>Clientes</a><a>Serviços</a><a>Barbeiros</a><a>Assistente IA</a><a>Configurações</a></nav><button className="logout" onClick={()=>supabase?.auth.signOut()}>Sair</button></aside><main><header><div><p className="eyebrow">TENVYQA BUSINESS</p><h1>Visão geral</h1><p>Atendimento inteligente. Sua barbearia nunca para.</p></div><div className={"status "+(isSupabaseConfigured?"ok":"")}><span></span>{isSupabaseConfigured?"Sistema conectado":"Configure o Supabase"}</div></header><section className="grid">{cards.map(([label,value,Icon])=><article key={label}><div className="icon"><Icon size={20}/></div><p>{label}</p><strong>{value}</strong></article>)}</section><section className="hero"><div><div className="pill"><Sparkles size={16}/> Assistente IA</div><h2>Configure a operação da {shop.name}.</h2><p>Agora podemos cadastrar serviços, barbeiros e horários. Depois, a IA usará somente esses dados reais para atender e agendar.</p><button>Continuar configuração</button></div><div className="phone"><div className="bubble">Olá! 👋 Como posso ajudar com seu agendamento?</div><div className="bubble customer">Tem horário amanhã para corte?</div><div className="bubble">Vou consultar os horários disponíveis. ✂️</div></div></section></main></div>}

export default function App(){const [session,setSession]=useState<Session|null>(null);const [shop,setShop]=useState<Shop|null>(null);const [loading,setLoading]=useState(true);useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next);if(!next)setShop(null)});return()=>data.subscription.unsubscribe()},[]);useEffect(()=>{async function load(){if(!session||!supabase){setLoading(false);return}setLoading(true);const {data}=await supabase.from("barbershop_members").select("barbershop_id, barbershops(id,name)").eq("user_id",session.user.id).limit(1).maybeSingle();const relation=data?.barbershops as unknown as Shop|null;if(relation)setShop(relation);setLoading(false)}load()},[session]);if(loading)return <div className="loading">TENVYQA</div>;if(!session)return <Auth/>;if(!shop)return <Onboarding onDone={setShop}/>;return <Dashboard shop={shop}/>;}